import { Lesson } from '@/types';

// Advanced Module - 10 Lessons
const advancedLessons: Lesson[] = [
    // Lesson 64: Common English Words
    {
        id: 'adv-64-common',
        title: 'Top 100 Common Words',
        description: 'Practice the most frequently used English words',
        category: 'advanced',
        keys: [],
        targetWpm: 50,
        targetAccuracy: 92,
        exercises: [
            { id: 'a64-1', text: 'the of and to a in is it you that', difficulty: 'intermediate' },
            { id: 'a64-2', text: 'he was for on are as with his they', difficulty: 'intermediate' },
            { id: 'a64-3', text: 'at be this have from or one had by', difficulty: 'intermediate' },
            { id: 'a64-4', text: 'but not what all were we when your', difficulty: 'intermediate' },
            { id: 'a64-5', text: 'can said there use an each which she', difficulty: 'advanced' },
            { id: 'a64-6', text: 'the quick brown fox jumps over lazy dog', difficulty: 'advanced' },
            { id: 'a64-7', text: 'how their if will up other about out many', difficulty: 'advanced' },
            { id: 'a64-8', text: 'then them these so some her would make like', difficulty: 'advanced' },
            { id: 'a64-9', text: 'him into time has look two more write go see', difficulty: 'advanced' },
            { id: 'a64-10', text: 'number no way could people my than first water', difficulty: 'advanced' },
        ],
    },
    // Lesson 65: Coding Practice (HTML/CSS)
    {
        id: 'adv-65-html',
        title: 'Coding: HTML/CSS',
        description: 'Practice typing HTML and CSS code',
        category: 'advanced',
        keys: [],
        targetWpm: 40,
        targetAccuracy: 90,
        exercises: [
            { id: 'a65-1', text: '<html> <head> <body> </html>', difficulty: 'intermediate' },
            { id: 'a65-2', text: '<div class="container"> </div>', difficulty: 'intermediate' },
            { id: 'a65-3', text: '<p id="main">Hello World</p>', difficulty: 'intermediate' },
            { id: 'a65-4', text: '<a href="https://example.com">Link</a>', difficulty: 'intermediate' },
            { id: 'a65-5', text: '.container { display: flex; }', difficulty: 'advanced' },
            { id: 'a65-6', text: '#header { background-color: #fff; }', difficulty: 'advanced' },
            { id: 'a65-7', text: 'margin: 0 auto; padding: 10px 20px;', difficulty: 'advanced' },
            { id: 'a65-8', text: '@media (max-width: 768px) { }', difficulty: 'advanced' },
            { id: 'a65-9', text: '<button class="btn btn-primary">Click</button>', difficulty: 'advanced' },
            { id: 'a65-10', text: '<input type="text" placeholder="Enter name" />', difficulty: 'advanced' },
        ],
    },
    // Lesson 66: Coding Practice (JavaScript)
    {
        id: 'adv-66-js',
        title: 'Coding: JavaScript',
        description: 'Practice typing JavaScript code',
        category: 'advanced',
        keys: [],
        targetWpm: 40,
        targetAccuracy: 90,
        exercises: [
            { id: 'a66-1', text: 'const x = 10; let y = 20;', difficulty: 'intermediate' },
            { id: 'a66-2', text: 'function add(a, b) { return a + b; }', difficulty: 'intermediate' },
            { id: 'a66-3', text: 'const arr = [1, 2, 3, 4, 5];', difficulty: 'intermediate' },
            { id: 'a66-4', text: 'if (x > 10) { console.log("yes"); }', difficulty: 'intermediate' },
            { id: 'a66-5', text: 'const obj = { name: "John", age: 30 };', difficulty: 'advanced' },
            { id: 'a66-6', text: 'arr.map((item) => item * 2);', difficulty: 'advanced' },
            { id: 'a66-7', text: 'async function fetchData() { await fetch(url); }', difficulty: 'advanced' },
            { id: 'a66-8', text: 'const { name, age } = person;', difficulty: 'advanced' },
            { id: 'a66-9', text: 'export default function App() { return <div />; }', difficulty: 'advanced' },
            { id: 'a66-10', text: 'const result = await Promise.all(promises);', difficulty: 'advanced' },
        ],
    },
    // Lesson 67: Coding Practice (Python)
    {
        id: 'adv-67-python',
        title: 'Coding: Python',
        description: 'Practice typing Python code',
        category: 'advanced',
        keys: [],
        targetWpm: 40,
        targetAccuracy: 90,
        exercises: [
            { id: 'a67-1', text: 'x = 10; y = 20; z = x + y', difficulty: 'intermediate' },
            { id: 'a67-2', text: 'def add(a, b): return a + b', difficulty: 'intermediate' },
            { id: 'a67-3', text: 'my_list = [1, 2, 3, 4, 5]', difficulty: 'intermediate' },
            { id: 'a67-4', text: 'if x > 10: print("yes")', difficulty: 'intermediate' },
            { id: 'a67-5', text: 'for i in range(10): print(i)', difficulty: 'advanced' },
            { id: 'a67-6', text: 'my_dict = {"name": "John", "age": 30}', difficulty: 'advanced' },
            { id: 'a67-7', text: 'class Person: def __init__(self): pass', difficulty: 'advanced' },
            { id: 'a67-8', text: 'import numpy as np; import pandas as pd', difficulty: 'advanced' },
            { id: 'a67-9', text: 'result = [x * 2 for x in my_list]', difficulty: 'advanced' },
            { id: 'a67-10', text: 'with open("file.txt", "r") as f: data = f.read()', difficulty: 'advanced' },
        ],
    },
    // Lesson 68: Email and Professional Writing
    {
        id: 'adv-68-email',
        title: 'Professional Email',
        description: 'Practice writing professional emails',
        category: 'advanced',
        keys: [],
        targetWpm: 45,
        targetAccuracy: 95,
        exercises: [
            { id: 'a68-1', text: 'Dear Sir or Madam,', difficulty: 'intermediate' },
            { id: 'a68-2', text: 'Thank you for your email.', difficulty: 'intermediate' },
            { id: 'a68-3', text: 'I hope this message finds you well.', difficulty: 'intermediate' },
            { id: 'a68-4', text: 'Please find attached the requested document.', difficulty: 'intermediate' },
            { id: 'a68-5', text: 'I am writing to inquire about your services.', difficulty: 'advanced' },
            { id: 'a68-6', text: 'Please let me know if you have any questions.', difficulty: 'advanced' },
            { id: 'a68-7', text: 'I look forward to hearing from you soon.', difficulty: 'advanced' },
            { id: 'a68-8', text: 'Best regards, John Smith', difficulty: 'advanced' },
            { id: 'a68-9', text: 'Thank you for your time and consideration.', difficulty: 'advanced' },
            { id: 'a68-10', text: 'Please do not hesitate to contact me if you need further information.', difficulty: 'advanced' },
        ],
    },
    // Lesson 69: Creative Writing
    {
        id: 'adv-69-creative',
        title: 'Creative Writing',
        description: 'Practice creative writing passages',
        category: 'advanced',
        keys: [],
        targetWpm: 45,
        targetAccuracy: 93,
        exercises: [
            { id: 'a69-1', text: 'The sun rose slowly over the distant hills.', difficulty: 'intermediate' },
            { id: 'a69-2', text: 'She walked through the quiet forest alone.', difficulty: 'intermediate' },
            { id: 'a69-3', text: 'The old clock on the wall struck midnight.', difficulty: 'intermediate' },
            { id: 'a69-4', text: 'Rain fell gently on the windowpane.', difficulty: 'intermediate' },
            { id: 'a69-5', text: 'Once upon a time, in a land far away, there lived a young princess.', difficulty: 'advanced' },
            { id: 'a69-6', text: 'The detective examined the evidence carefully.', difficulty: 'advanced' },
            { id: 'a69-7', text: 'Stars twinkled in the vast night sky above.', difficulty: 'advanced' },
            { id: 'a69-8', text: 'The adventure was about to begin, and nothing would ever be the same.', difficulty: 'advanced' },
            { id: 'a69-9', text: 'With a deep breath, she opened the mysterious door.', difficulty: 'advanced' },
            { id: 'a69-10', text: 'The dragon spread its wings and soared into the clouds above the kingdom.', difficulty: 'advanced' },
        ],
    },
    // Lesson 70: Speed Typing - 60 WPM Goal
    {
        id: 'adv-70-speed60',
        title: 'Speed Goal: 60 WPM',
        description: 'Push your speed to 60 words per minute',
        category: 'advanced',
        keys: [],
        targetWpm: 60,
        targetAccuracy: 90,
        exercises: [
            { id: 'a70-1', text: 'the quick brown fox jumps over the lazy dog', difficulty: 'intermediate' },
            { id: 'a70-2', text: 'pack my box with five dozen liquor jugs', difficulty: 'intermediate' },
            { id: 'a70-3', text: 'how vexingly quick daft zebras jump', difficulty: 'intermediate' },
            { id: 'a70-4', text: 'sphinx of black quartz judge my vow', difficulty: 'intermediate' },
            { id: 'a70-5', text: 'the five boxing wizards jump quickly at dawn', difficulty: 'advanced' },
            { id: 'a70-6', text: 'jinxed wizards pluck ivy from the big quilt', difficulty: 'advanced' },
            { id: 'a70-7', text: 'crazy frederick bought many very exquisite opal jewels', difficulty: 'advanced' },
            { id: 'a70-8', text: 'we promptly judged antique ivory buckles for the next prize', difficulty: 'advanced' },
            { id: 'a70-9', text: 'a quick movement of the enemy will jeopardize six gunboats', difficulty: 'advanced' },
            { id: 'a70-10', text: 'few quips galvanized the mock jury box sending shockwaves everywhere', difficulty: 'advanced' },
        ],
    },
    // Lesson 71: Speed Typing - 70 WPM Goal
    {
        id: 'adv-71-speed70',
        title: 'Speed Goal: 70 WPM',
        description: 'Push your speed to 70 words per minute',
        category: 'advanced',
        keys: [],
        targetWpm: 70,
        targetAccuracy: 88,
        exercises: [
            { id: 'a71-1', text: 'the quick brown fox jumps over the lazy sleeping dog in the yard', difficulty: 'advanced' },
            { id: 'a71-2', text: 'pack my box with five dozen liquor jugs and keep them cold', difficulty: 'advanced' },
            { id: 'a71-3', text: 'amazingly few discotheques provide jukeboxes that work properly', difficulty: 'advanced' },
            { id: 'a71-4', text: 'how razorback jumping frogs can level six piqued gymnasts quickly', difficulty: 'advanced' },
            { id: 'a71-5', text: 'a wizard quick study of lexicography chugs five jam bottles', difficulty: 'advanced' },
            { id: 'a71-6', text: 'jackdaws love my big sphinx of quartz placed near the fountain', difficulty: 'advanced' },
            { id: 'a71-7', text: 'big july earthquakes confound zany experimental vow', difficulty: 'advanced' },
            { id: 'a71-8', text: 'foxy parsons quiz and cajole the lovably dim wiki host', difficulty: 'advanced' },
            { id: 'a71-9', text: 'the job requires extra pluck and zeal from every young wage earner', difficulty: 'advanced' },
            { id: 'a71-10', text: 'grumpy wizards make toxic brew for the evil queen and jack', difficulty: 'advanced' },
        ],
    },
    // Lesson 72: Accuracy Challenge
    {
        id: 'adv-72-accuracy',
        title: 'Accuracy Challenge: 98%+',
        description: 'Focus on achieving 98% accuracy',
        category: 'advanced',
        keys: [],
        targetWpm: 40,
        targetAccuracy: 98,
        exercises: [
            { id: 'a72-1', text: 'accuracy is more important than speed', difficulty: 'intermediate' },
            { id: 'a72-2', text: 'slow down to speed up your typing', difficulty: 'intermediate' },
            { id: 'a72-3', text: 'focus on each key as you press it', difficulty: 'intermediate' },
            { id: 'a72-4', text: 'muscle memory builds with practice', difficulty: 'intermediate' },
            { id: 'a72-5', text: 'take your time and type each word carefully', difficulty: 'advanced' },
            { id: 'a72-6', text: 'precision typing leads to faster typing over time', difficulty: 'advanced' },
            { id: 'a72-7', text: 'every mistake slows you down more than careful typing', difficulty: 'advanced' },
            { id: 'a72-8', text: 'breathe deeply and maintain a steady rhythm', difficulty: 'advanced' },
            { id: 'a72-9', text: 'your fingers know where the keys are just trust them', difficulty: 'advanced' },
            { id: 'a72-10', text: 'with perfect accuracy speed will naturally follow', difficulty: 'advanced' },
        ],
    },
    // Lesson 73: Ultimate Master Challenge
    {
        id: 'adv-73-master',
        title: 'Ultimate Master Challenge',
        description: 'The final typing mastery challenge',
        category: 'advanced',
        keys: [],
        targetWpm: 75,
        targetAccuracy: 95,
        exercises: [
            { id: 'a73-1', text: 'The quick brown fox jumps over the lazy dog near the riverbank.', difficulty: 'advanced' },
            { id: 'a73-2', text: 'Pack my box with five dozen liquor jugs for the celebration tonight.', difficulty: 'advanced' },
            { id: 'a73-3', text: 'How vexingly quick daft zebras jump across the open savanna plains!', difficulty: 'advanced' },
            { id: 'a73-4', text: 'Sphinx of black quartz, judge my vow to type perfectly every day.', difficulty: 'advanced' },
            { id: 'a73-5', text: 'The five boxing wizards jump quickly at dawn to begin their training.', difficulty: 'advanced' },
            { id: 'a73-6', text: 'Crazy Frederick bought many very exquisite opal jewels at the market.', difficulty: 'advanced' },
            { id: 'a73-7', text: 'We promptly judged antique ivory buckles for the next typing prize.', difficulty: 'advanced' },
            { id: 'a73-8', text: 'Jackdaws love my big sphinx of quartz placed near the old fountain.', difficulty: 'advanced' },
            { id: 'a73-9', text: 'The job requires extra pluck and zeal from every dedicated typist here.', difficulty: 'advanced' },
            { id: 'a73-10', text: 'Congratulations! You have mastered the art of typing. Keep practicing!', difficulty: 'advanced' },
        ],
    },
];

export { advancedLessons };
