import { Lesson } from '@/types';

// Bottom Row Module - 12 Lessons
const bottomRowLessons: Lesson[] = [
    // Lesson 36: V Key
    {
        id: 'bot-36-v',
        title: 'Master the V Key',
        description: 'Learn V key extending from F',
        category: 'bottom-row-basics',
        keys: ['v', 'f'],
        targetWpm: 25,
        targetAccuracy: 92,
        exercises: [
            { id: 'b36-1', text: 'vvv vvv vvv vvv vvv vvv', difficulty: 'beginner' },
            { id: 'b36-2', text: 'fvf fvf fvf fvf fvf fvf', difficulty: 'beginner' },
            { id: 'b36-3', text: 'vfv vfv vfv vfv vfv vfv', difficulty: 'beginner' },
            { id: 'b36-4', text: 'vf vf vf vf vf vf vf vf', difficulty: 'beginner' },
            { id: 'b36-5', text: 'fv fv fv fv fv fv fv fv', difficulty: 'intermediate' },
            { id: 'b36-6', text: 'vvvv ffff vvvv ffff vvvv', difficulty: 'intermediate' },
            { id: 'b36-7', text: 'vfvf vfvf vfvf vfvf vfvf', difficulty: 'intermediate' },
            { id: 'b36-8', text: 'have gave save drive five', difficulty: 'advanced' },
            { id: 'b36-9', text: 'ever over every river live', difficulty: 'advanced' },
            { id: 'b36-10', text: 'drive the river; give five; save every life', difficulty: 'advanced' },
        ],
    },
    // Lesson 37: M Key
    {
        id: 'bot-37-m',
        title: 'Master the M Key',
        description: 'Learn M key extending from J',
        category: 'bottom-row-basics',
        keys: ['m', 'j'],
        targetWpm: 25,
        targetAccuracy: 92,
        exercises: [
            { id: 'b37-1', text: 'mmm mmm mmm mmm mmm mmm', difficulty: 'beginner' },
            { id: 'b37-2', text: 'jmj jmj jmj jmj jmj jmj', difficulty: 'beginner' },
            { id: 'b37-3', text: 'mjm mjm mjm mjm mjm mjm', difficulty: 'beginner' },
            { id: 'b37-4', text: 'mj mj mj mj mj mj mj mj', difficulty: 'beginner' },
            { id: 'b37-5', text: 'jm jm jm jm jm jm jm jm', difficulty: 'intermediate' },
            { id: 'b37-6', text: 'mmmm jjjj mmmm jjjj mmmm', difficulty: 'intermediate' },
            { id: 'b37-7', text: 'mjmj mjmj mjmj mjmj mjmj', difficulty: 'intermediate' },
            { id: 'b37-8', text: 'make made more most must', difficulty: 'advanced' },
            { id: 'b37-9', text: 'room home some time game', difficulty: 'advanced' },
            { id: 'b37-10', text: 'make more time; some must make room', difficulty: 'advanced' },
        ],
    },
    // Lesson 38: V and M
    {
        id: 'bot-38-vm',
        title: 'V and M Together',
        description: 'Practice V and M keys together',
        category: 'bottom-row-basics',
        keys: ['v', 'm', 'f', 'j'],
        targetWpm: 28,
        targetAccuracy: 91,
        exercises: [
            { id: 'b38-1', text: 'vm vm vm vm vm vm vm vm', difficulty: 'beginner' },
            { id: 'b38-2', text: 'mv mv mv mv mv mv mv mv', difficulty: 'beginner' },
            { id: 'b38-3', text: 'vmvm vmvm vmvm vmvm vmvm', difficulty: 'beginner' },
            { id: 'b38-4', text: 'mvmv mvmv mvmv mvmv mvmv', difficulty: 'beginner' },
            { id: 'b38-5', text: 'move move movie movie', difficulty: 'intermediate' },
            { id: 'b38-6', text: 'vim vim vim vim vim vim', difficulty: 'intermediate' },
            { id: 'b38-7', text: 'move vim move vim move', difficulty: 'intermediate' },
            { id: 'b38-8', text: 'move them; gave more vim', difficulty: 'advanced' },
            { id: 'b38-9', text: 'movement movement movement', difficulty: 'advanced' },
            { id: 'b38-10', text: 'vim vim; move vim; give them movies', difficulty: 'advanced' },
        ],
    },
    // Lesson 39: C Key
    {
        id: 'bot-39-c',
        title: 'Master the C Key',
        description: 'Learn C key extending from D',
        category: 'bottom-row-basics',
        keys: ['c', 'd'],
        targetWpm: 25,
        targetAccuracy: 92,
        exercises: [
            { id: 'b39-1', text: 'ccc ccc ccc ccc ccc ccc', difficulty: 'beginner' },
            { id: 'b39-2', text: 'dcd dcd dcd dcd dcd dcd', difficulty: 'beginner' },
            { id: 'b39-3', text: 'cdc cdc cdc cdc cdc cdc', difficulty: 'beginner' },
            { id: 'b39-4', text: 'cd cd cd cd cd cd cd cd', difficulty: 'beginner' },
            { id: 'b39-5', text: 'dc dc dc dc dc dc dc dc', difficulty: 'intermediate' },
            { id: 'b39-6', text: 'cccc dddd cccc dddd cccc', difficulty: 'intermediate' },
            { id: 'b39-7', text: 'cdcd cdcd cdcd cdcd cdcd', difficulty: 'intermediate' },
            { id: 'b39-8', text: 'can could come call care', difficulty: 'advanced' },
            { id: 'b39-9', text: 'deck clock check rice comic', difficulty: 'advanced' },
            { id: 'b39-10', text: 'can you come; check the clock; care for rice', difficulty: 'advanced' },
        ],
    },
    // Lesson 40: N Key
    {
        id: 'bot-40-n',
        title: 'Master the N Key',
        description: 'Learn N key extending from J',
        category: 'bottom-row-basics',
        keys: ['n', 'j'],
        targetWpm: 25,
        targetAccuracy: 92,
        exercises: [
            { id: 'b40-1', text: 'nnn nnn nnn nnn nnn nnn', difficulty: 'beginner' },
            { id: 'b40-2', text: 'jnj jnj jnj jnj jnj jnj', difficulty: 'beginner' },
            { id: 'b40-3', text: 'njn njn njn njn njn njn', difficulty: 'beginner' },
            { id: 'b40-4', text: 'nj nj nj nj nj nj nj nj', difficulty: 'beginner' },
            { id: 'b40-5', text: 'jn jn jn jn jn jn jn jn', difficulty: 'intermediate' },
            { id: 'b40-6', text: 'nnnn jjjj nnnn jjjj nnnn', difficulty: 'intermediate' },
            { id: 'b40-7', text: 'njnj njnj njnj njnj njnj', difficulty: 'intermediate' },
            { id: 'b40-8', text: 'new now never none night', difficulty: 'advanced' },
            { id: 'b40-9', text: 'ran then nine fine line', difficulty: 'advanced' },
            { id: 'b40-10', text: 'new night; then nine ran; fine line now', difficulty: 'advanced' },
        ],
    },
    // Lesson 41: C and N
    {
        id: 'bot-41-cn',
        title: 'C and N Together',
        description: 'Practice C and N keys together',
        category: 'bottom-row-intermediate',
        keys: ['c', 'n', 'd', 'j'],
        targetWpm: 28,
        targetAccuracy: 91,
        exercises: [
            { id: 'b41-1', text: 'cn cn cn cn cn cn cn cn', difficulty: 'beginner' },
            { id: 'b41-2', text: 'nc nc nc nc nc nc nc nc', difficulty: 'beginner' },
            { id: 'b41-3', text: 'cncn cncn cncn cncn cncn', difficulty: 'beginner' },
            { id: 'b41-4', text: 'ncnc ncnc ncnc ncnc ncnc', difficulty: 'beginner' },
            { id: 'b41-5', text: 'once once dance dance', difficulty: 'intermediate' },
            { id: 'b41-6', text: 'cancel cancel cancel cancel', difficulty: 'intermediate' },
            { id: 'b41-7', text: 'incline incline incline', difficulty: 'intermediate' },
            { id: 'b41-8', text: 'nice nice since since', difficulty: 'advanced' },
            { id: 'b41-9', text: 'chance chance announce', difficulty: 'advanced' },
            { id: 'b41-10', text: 'once nice chance; since the dance announced', difficulty: 'advanced' },
        ],
    },
    // Lesson 42: X Key
    {
        id: 'bot-42-x',
        title: 'Master the X Key',
        description: 'Learn X key extending from S',
        category: 'bottom-row-intermediate',
        keys: ['x', 's'],
        targetWpm: 22,
        targetAccuracy: 90,
        exercises: [
            { id: 'b42-1', text: 'xxx xxx xxx xxx xxx xxx', difficulty: 'beginner' },
            { id: 'b42-2', text: 'sxs sxs sxs sxs sxs sxs', difficulty: 'beginner' },
            { id: 'b42-3', text: 'xsx xsx xsx xsx xsx xsx', difficulty: 'beginner' },
            { id: 'b42-4', text: 'xs xs xs xs xs xs xs xs', difficulty: 'beginner' },
            { id: 'b42-5', text: 'sx sx sx sx sx sx sx sx', difficulty: 'intermediate' },
            { id: 'b42-6', text: 'xxxx ssss xxxx ssss xxxx', difficulty: 'intermediate' },
            { id: 'b42-7', text: 'xsxs xsxs xsxs xsxs xsxs', difficulty: 'intermediate' },
            { id: 'b42-8', text: 'fix six mix max wax tax', difficulty: 'advanced' },
            { id: 'b42-9', text: 'next text exit extra relax', difficulty: 'advanced' },
            { id: 'b42-10', text: 'fix the next six; max tax relax', difficulty: 'advanced' },
        ],
    },
    // Lesson 43: Comma Key
    {
        id: 'bot-43-comma',
        title: 'Master the Comma Key',
        description: 'Learn comma key extending from K',
        category: 'bottom-row-intermediate',
        keys: [',', 'k'],
        targetWpm: 22,
        targetAccuracy: 90,
        exercises: [
            { id: 'b43-1', text: ',,, ,,, ,,, ,,, ,,, ,,,', difficulty: 'beginner' },
            { id: 'b43-2', text: 'k,k k,k k,k k,k k,k k,k', difficulty: 'beginner' },
            { id: 'b43-3', text: ',k, ,k, ,k, ,k, ,k, ,k,', difficulty: 'beginner' },
            { id: 'b43-4', text: 'k, k, k, k, k, k, k, k,', difficulty: 'beginner' },
            { id: 'b43-5', text: ',k ,k ,k ,k ,k ,k ,k ,k', difficulty: 'intermediate' },
            { id: 'b43-6', text: 'a, s, d, f, j, k, l, ;,', difficulty: 'intermediate' },
            { id: 'b43-7', text: 'red, blue, green, yellow, orange', difficulty: 'intermediate' },
            { id: 'b43-8', text: 'run, jump, skip, hop, walk', difficulty: 'advanced' },
            { id: 'b43-9', text: 'first, second, third, fourth, fifth', difficulty: 'advanced' },
            { id: 'b43-10', text: 'one, two, three, four, five, six, seven, eight', difficulty: 'advanced' },
        ],
    },
    // Lesson 44: Z Key
    {
        id: 'bot-44-z',
        title: 'Master the Z Key',
        description: 'Learn Z key extending from A',
        category: 'bottom-row-intermediate',
        keys: ['z', 'a'],
        targetWpm: 20,
        targetAccuracy: 90,
        exercises: [
            { id: 'b44-1', text: 'zzz zzz zzz zzz zzz zzz', difficulty: 'beginner' },
            { id: 'b44-2', text: 'aza aza aza aza aza aza', difficulty: 'beginner' },
            { id: 'b44-3', text: 'zaz zaz zaz zaz zaz zaz', difficulty: 'beginner' },
            { id: 'b44-4', text: 'za za za za za za za za', difficulty: 'beginner' },
            { id: 'b44-5', text: 'az az az az az az az az', difficulty: 'intermediate' },
            { id: 'b44-6', text: 'zzzz aaaa zzzz aaaa zzzz', difficulty: 'intermediate' },
            { id: 'b44-7', text: 'zaza zaza zaza zaza zaza', difficulty: 'intermediate' },
            { id: 'b44-8', text: 'zoo zone zero zest jazz', difficulty: 'advanced' },
            { id: 'b44-9', text: 'size prize freeze breeze', difficulty: 'advanced' },
            { id: 'b44-10', text: 'the jazz zone; zero size prize freeze', difficulty: 'advanced' },
        ],
    },
    // Lesson 45: Period Key
    {
        id: 'bot-45-period',
        title: 'Master the Period Key',
        description: 'Learn period key extending from L',
        category: 'bottom-row-intermediate',
        keys: ['.', 'l'],
        targetWpm: 22,
        targetAccuracy: 90,
        exercises: [
            { id: 'b45-1', text: '... ... ... ... ... ...', difficulty: 'beginner' },
            { id: 'b45-2', text: 'l.l l.l l.l l.l l.l l.l', difficulty: 'beginner' },
            { id: 'b45-3', text: '.l. .l. .l. .l. .l. .l.', difficulty: 'beginner' },
            { id: 'b45-4', text: 'l. l. l. l. l. l. l. l.', difficulty: 'beginner' },
            { id: 'b45-5', text: '.l .l .l .l .l .l .l .l', difficulty: 'intermediate' },
            { id: 'b45-6', text: 'a. s. d. f. j. k. l.', difficulty: 'intermediate' },
            { id: 'b45-7', text: 'Run. Jump. Skip. Hop.', difficulty: 'intermediate' },
            { id: 'b45-8', text: 'Stop. Go. Wait. Run.', difficulty: 'advanced' },
            { id: 'b45-9', text: 'Hello. Hi. Hey. Good.', difficulty: 'advanced' },
            { id: 'b45-10', text: 'I run. You jump. We skip. They hop.', difficulty: 'advanced' },
        ],
    },
    // Lesson 46: B Key
    {
        id: 'bot-46-b',
        title: 'Master the B Key',
        description: 'Learn B key extending from F',
        category: 'bottom-row-advanced',
        keys: ['b', 'f'],
        targetWpm: 25,
        targetAccuracy: 91,
        exercises: [
            { id: 'b46-1', text: 'bbb bbb bbb bbb bbb bbb', difficulty: 'beginner' },
            { id: 'b46-2', text: 'fbf fbf fbf fbf fbf fbf', difficulty: 'beginner' },
            { id: 'b46-3', text: 'bfb bfb bfb bfb bfb bfb', difficulty: 'beginner' },
            { id: 'b46-4', text: 'bf bf bf bf bf bf bf bf', difficulty: 'beginner' },
            { id: 'b46-5', text: 'fb fb fb fb fb fb fb fb', difficulty: 'intermediate' },
            { id: 'b46-6', text: 'bbbb ffff bbbb ffff bbbb', difficulty: 'intermediate' },
            { id: 'b46-7', text: 'bfbf bfbf bfbf bfbf bfbf', difficulty: 'intermediate' },
            { id: 'b46-8', text: 'be been been be big big', difficulty: 'advanced' },
            { id: 'b46-9', text: 'blue brown black bright', difficulty: 'advanced' },
            { id: 'b46-10', text: 'the big blue bird; brown bright building', difficulty: 'advanced' },
        ],
    },
    // Lesson 47: Slash Key
    {
        id: 'bot-47-slash',
        title: 'Master the / Key',
        description: 'Learn slash key extending from semicolon',
        category: 'bottom-row-advanced',
        keys: ['/', ';'],
        targetWpm: 22,
        targetAccuracy: 90,
        exercises: [
            { id: 'b47-1', text: '/// /// /// /// /// ///', difficulty: 'beginner' },
            { id: 'b47-2', text: ';/; ;/; ;/; ;/; ;/; ;/;', difficulty: 'beginner' },
            { id: 'b47-3', text: '/;/ /;/ /;/ /;/ /;/ /;/', difficulty: 'beginner' },
            { id: 'b47-4', text: '/; /; /; /; /; /; /; /;', difficulty: 'beginner' },
            { id: 'b47-5', text: ';/ ;/ ;/ ;/ ;/ ;/ ;/ ;/', difficulty: 'intermediate' },
            { id: 'b47-6', text: '//// ;;;; //// ;;;; ////', difficulty: 'intermediate' },
            { id: 'b47-7', text: '/;/; /;/; /;/; /;/; /;/;', difficulty: 'intermediate' },
            { id: 'b47-8', text: 'and/or; yes/no; true/false', difficulty: 'advanced' },
            { id: 'b47-9', text: 'http://; ftp://; file://', difficulty: 'advanced' },
            { id: 'b47-10', text: 'a/b/c/d/e; 1/2/3/4/5', difficulty: 'advanced' },
        ],
    },
];

export { bottomRowLessons };
