import { Lesson } from '@/types';

// ============================================================================
// HOME ROW MODULE - 20 Lessons
// ============================================================================

const homeRowLessons: Lesson[] = [
    // Lesson 1: F Key Mastery
    {
        id: 'home-1-f',
        title: 'Master the F Key',
        description: 'Learn the F key with left index finger',
        category: 'home-row-basics',
        keys: ['f'],
        targetWpm: 20,
        targetAccuracy: 95,
        exercises: [
            { id: 'h1-1', text: 'fff fff fff fff fff fff fff fff', difficulty: 'beginner' },
            { id: 'h1-2', text: 'fff fff fff fff fff fff fff fff fff fff', difficulty: 'beginner' },
            { id: 'h1-3', text: 'f f f f f f f f f f f f f f f f', difficulty: 'beginner' },
            { id: 'h1-4', text: 'fff f fff f fff f fff f fff f', difficulty: 'beginner' },
            { id: 'h1-5', text: 'ff ff ff ff ff ff ff ff ff ff', difficulty: 'beginner' },
            { id: 'h1-6', text: 'fffff fffff fffff fffff fffff', difficulty: 'intermediate' },
            { id: 'h1-7', text: 'f ff fff ffff fffff f ff fff', difficulty: 'intermediate' },
            { id: 'h1-8', text: 'fff fff fff fff fff fff fff fff fff fff fff fff', difficulty: 'intermediate' },
            { id: 'h1-9', text: 'ffffffffff ffffffffff ffffffffff', difficulty: 'intermediate' },
            { id: 'h1-10', text: 'ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff', difficulty: 'intermediate' },
        ],
    },
    // Lesson 2: J Key Mastery
    {
        id: 'home-2-j',
        title: 'Master the J Key',
        description: 'Learn the J key with right index finger',
        category: 'home-row-basics',
        keys: ['j'],
        targetWpm: 20,
        targetAccuracy: 95,
        exercises: [
            { id: 'h2-1', text: 'jjj jjj jjj jjj jjj jjj jjj jjj', difficulty: 'beginner' },
            { id: 'h2-2', text: 'jjj jjj jjj jjj jjj jjj jjj jjj jjj jjj', difficulty: 'beginner' },
            { id: 'h2-3', text: 'j j j j j j j j j j j j j j j j', difficulty: 'beginner' },
            { id: 'h2-4', text: 'jjj j jjj j jjj j jjj j jjj j', difficulty: 'beginner' },
            { id: 'h2-5', text: 'jj jj jj jj jj jj jj jj jj jj', difficulty: 'beginner' },
            { id: 'h2-6', text: 'jjjjj jjjjj jjjjj jjjjj jjjjj', difficulty: 'intermediate' },
            { id: 'h2-7', text: 'j jj jjj jjjj jjjjj j jj jjj', difficulty: 'intermediate' },
            { id: 'h2-8', text: 'jjj jjj jjj jjj jjj jjj jjj jjj jjj jjj jjj jjj', difficulty: 'intermediate' },
            { id: 'h2-9', text: 'jjjjjjjjjj jjjjjjjjjj jjjjjjjjjj', difficulty: 'intermediate' },
            { id: 'h2-10', text: 'jj jj jj jj jj jj jj jj jj jj jj jj jj jj jj', difficulty: 'intermediate' },
        ],
    },
    // Lesson 3: F and J Combination
    {
        id: 'home-3-fj',
        title: 'F and J Together',
        description: 'Alternate between F and J keys',
        category: 'home-row-basics',
        keys: ['f', 'j'],
        targetWpm: 25,
        targetAccuracy: 93,
        exercises: [
            { id: 'h3-1', text: 'fj fj fj fj fj fj fj fj', difficulty: 'beginner' },
            { id: 'h3-2', text: 'jf jf jf jf jf jf jf jf', difficulty: 'beginner' },
            { id: 'h3-3', text: 'fjfj fjfj fjfj fjfj fjfj', difficulty: 'beginner' },
            { id: 'h3-4', text: 'jfjf jfjf jfjf jfjf jfjf', difficulty: 'beginner' },
            { id: 'h3-5', text: 'fff jjj fff jjj fff jjj', difficulty: 'intermediate' },
            { id: 'h3-6', text: 'fjfjfj fjfjfj fjfjfj fjfjfj', difficulty: 'intermediate' },
            { id: 'h3-7', text: 'jfjfjf jfjfjf jfjfjf jfjfjf', difficulty: 'intermediate' },
            { id: 'h3-8', text: 'ff jj ff jj ff jj ff jj', difficulty: 'intermediate' },
            { id: 'h3-9', text: 'fff jjj fff jjj fff jjj fff jjj fff jjj', difficulty: 'advanced' },
            { id: 'h3-10', text: 'fjfjfjfjfj fjfjfjfjfj fjfjfjfjfj', difficulty: 'advanced' },
        ],
    },
    // Lesson 4: D Key Mastery
    {
        id: 'home-4-d',
        title: 'Master the D Key',
        description: 'Learn the D key with left middle finger',
        category: 'home-row-basics',
        keys: ['d'],
        targetWpm: 20,
        targetAccuracy: 95,
        exercises: [
            { id: 'h4-1', text: 'ddd ddd ddd ddd ddd ddd ddd ddd', difficulty: 'beginner' },
            { id: 'h4-2', text: 'd d d d d d d d d d d d d d d d', difficulty: 'beginner' },
            { id: 'h4-3', text: 'dd dd dd dd dd dd dd dd dd dd', difficulty: 'beginner' },
            { id: 'h4-4', text: 'ddd d ddd d ddd d ddd d ddd d', difficulty: 'beginner' },
            { id: 'h4-5', text: 'ddddd ddddd ddddd ddddd ddddd', difficulty: 'beginner' },
            { id: 'h4-6', text: 'd dd ddd dddd ddddd d dd ddd', difficulty: 'intermediate' },
            { id: 'h4-7', text: 'ddd ddd ddd ddd ddd ddd ddd ddd ddd ddd ddd ddd', difficulty: 'intermediate' },
            { id: 'h4-8', text: 'dddddddddd dddddddddd dddddddddd', difficulty: 'intermediate' },
            { id: 'h4-9', text: 'dd dd dd dd dd dd dd dd dd dd dd dd dd dd dd', difficulty: 'intermediate' },
            { id: 'h4-10', text: 'ddd ddd ddd ddd ddd ddd ddd ddd ddd ddd', difficulty: 'intermediate' },
        ],
    },
    // Lesson 5: K Key Mastery
    {
        id: 'home-5-k',
        title: 'Master the K Key',
        description: 'Learn the K key with right middle finger',
        category: 'home-row-basics',
        keys: ['k'],
        targetWpm: 20,
        targetAccuracy: 95,
        exercises: [
            { id: 'h5-1', text: 'kkk kkk kkk kkk kkk kkk kkk kkk', difficulty: 'beginner' },
            { id: 'h5-2', text: 'k k k k k k k k k k k k k k k k', difficulty: 'beginner' },
            { id: 'h5-3', text: 'kk kk kk kk kk kk kk kk kk kk', difficulty: 'beginner' },
            { id: 'h5-4', text: 'kkk k kkk k kkk k kkk k kkk k', difficulty: 'beginner' },
            { id: 'h5-5', text: 'kkkkk kkkkk kkkkk kkkkk kkkkk', difficulty: 'beginner' },
            { id: 'h5-6', text: 'k kk kkk kkkk kkkkk k kk kkk', difficulty: 'intermediate' },
            { id: 'h5-7', text: 'kkk kkk kkk kkk kkk kkk kkk kkk kkk kkk kkk kkk', difficulty: 'intermediate' },
            { id: 'h5-8', text: 'kkkkkkkkkk kkkkkkkkkk kkkkkkkkkk', difficulty: 'intermediate' },
            { id: 'h5-9', text: 'kk kk kk kk kk kk kk kk kk kk kk kk kk kk kk', difficulty: 'intermediate' },
            { id: 'h5-10', text: 'kkk kkk kkk kkk kkk kkk kkk kkk kkk kkk', difficulty: 'intermediate' },
        ],
    },
    // Lesson 6: D and K Combination
    {
        id: 'home-6-dk',
        title: 'D and K Together',
        description: 'Alternate between D and K keys',
        category: 'home-row-basics',
        keys: ['d', 'k'],
        targetWpm: 25,
        targetAccuracy: 93,
        exercises: [
            { id: 'h6-1', text: 'dk dk dk dk dk dk dk dk', difficulty: 'beginner' },
            { id: 'h6-2', text: 'kd kd kd kd kd kd kd kd', difficulty: 'beginner' },
            { id: 'h6-3', text: 'dkdk dkdk dkdk dkdk dkdk', difficulty: 'beginner' },
            { id: 'h6-4', text: 'kdkd kdkd kdkd kdkd kdkd', difficulty: 'beginner' },
            { id: 'h6-5', text: 'ddd kkk ddd kkk ddd kkk', difficulty: 'intermediate' },
            { id: 'h6-6', text: 'dkdkdk dkdkdk dkdkdk dkdkdk', difficulty: 'intermediate' },
            { id: 'h6-7', text: 'kdkdkd kdkdkd kdkdkd kdkdkd', difficulty: 'intermediate' },
            { id: 'h6-8', text: 'dd kk dd kk dd kk dd kk', difficulty: 'intermediate' },
            { id: 'h6-9', text: 'ddd kkk ddd kkk ddd kkk ddd kkk ddd kkk', difficulty: 'advanced' },
            { id: 'h6-10', text: 'dkdkdkdkdk dkdkdkdkdk dkdkdkdkdk', difficulty: 'advanced' },
        ],
    },
    // Lesson 7: F, J, D, K Review
    {
        id: 'home-7-fjdk',
        title: 'Four Keys Review',
        description: 'Practice F, J, D, K together',
        category: 'home-row-basics',
        keys: ['f', 'j', 'd', 'k'],
        targetWpm: 30,
        targetAccuracy: 92,
        exercises: [
            { id: 'h7-1', text: 'fj dk fj dk fj dk fj dk', difficulty: 'beginner' },
            { id: 'h7-2', text: 'fd jk fd jk fd jk fd jk', difficulty: 'beginner' },
            { id: 'h7-3', text: 'fdk fjk fdk fjk fdk fjk', difficulty: 'intermediate' },
            { id: 'h7-4', text: 'jfd jkd jfd jkd jfd jkd', difficulty: 'intermediate' },
            { id: 'h7-5', text: 'fjdk fjdk fjdk fjdk fjdk', difficulty: 'intermediate' },
            { id: 'h7-6', text: 'dkfj dkfj dkfj dkfj dkfj', difficulty: 'intermediate' },
            { id: 'h7-7', text: 'fdjk fdjk fdjk fdjk fdjk', difficulty: 'advanced' },
            { id: 'h7-8', text: 'jkfd jkfd jkfd jkfd jkfd', difficulty: 'advanced' },
            { id: 'h7-9', text: 'ff jj dd kk ff jj dd kk ff jj dd kk', difficulty: 'advanced' },
            { id: 'h7-10', text: 'fjdk jkfd dkfj kfjd fjdk jkfd', difficulty: 'advanced' },
        ],
    },
    // Lesson 8: S Key Mastery
    {
        id: 'home-8-s',
        title: 'Master the S Key',
        description: 'Learn the S key with left ring finger',
        category: 'home-row-basics',
        keys: ['s'],
        targetWpm: 20,
        targetAccuracy: 95,
        exercises: [
            { id: 'h8-1', text: 'sss sss sss sss sss sss sss sss', difficulty: 'beginner' },
            { id: 'h8-2', text: 's s s s s s s s s s s s s s s s', difficulty: 'beginner' },
            { id: 'h8-3', text: 'ss ss ss ss ss ss ss ss ss ss', difficulty: 'beginner' },
            { id: 'h8-4', text: 'sss s sss s sss s sss s sss s', difficulty: 'beginner' },
            { id: 'h8-5', text: 'sssss sssss sssss sssss sssss', difficulty: 'beginner' },
            { id: 'h8-6', text: 's ss sss ssss sssss s ss sss', difficulty: 'intermediate' },
            { id: 'h8-7', text: 'sss sss sss sss sss sss sss sss sss sss sss sss', difficulty: 'intermediate' },
            { id: 'h8-8', text: 'ssssssssss ssssssssss ssssssssss', difficulty: 'intermediate' },
            { id: 'h8-9', text: 'ss ss ss ss ss ss ss ss ss ss ss ss ss ss ss', difficulty: 'intermediate' },
            { id: 'h8-10', text: 'sss sss sss sss sss sss sss sss sss sss', difficulty: 'intermediate' },
        ],
    },
    // Lesson 9: L Key Mastery
    {
        id: 'home-9-l',
        title: 'Master the L Key',
        description: 'Learn the L key with right ring finger',
        category: 'home-row-basics',
        keys: ['l'],
        targetWpm: 20,
        targetAccuracy: 95,
        exercises: [
            { id: 'h9-1', text: 'lll lll lll lll lll lll lll lll', difficulty: 'beginner' },
            { id: 'h9-2', text: 'l l l l l l l l l l l l l l l l', difficulty: 'beginner' },
            { id: 'h9-3', text: 'll ll ll ll ll ll ll ll ll ll', difficulty: 'beginner' },
            { id: 'h9-4', text: 'lll l lll l lll l lll l lll l', difficulty: 'beginner' },
            { id: 'h9-5', text: 'lllll lllll lllll lllll lllll', difficulty: 'beginner' },
            { id: 'h9-6', text: 'l ll lll llll lllll l ll lll', difficulty: 'intermediate' },
            { id: 'h9-7', text: 'lll lll lll lll lll lll lll lll lll lll lll lll', difficulty: 'intermediate' },
            { id: 'h9-8', text: 'llllllllll llllllllll llllllllll', difficulty: 'intermediate' },
            { id: 'h9-9', text: 'll ll ll ll ll ll ll ll ll ll ll ll ll ll ll', difficulty: 'intermediate' },
            { id: 'h9-10', text: 'lll lll lll lll lll lll lll lll lll lll', difficulty: 'intermediate' },
        ],
    },
    // Lesson 10: S and L Combination
    {
        id: 'home-10-sl',
        title: 'S and L Together',
        description: 'Alternate between S and L keys',
        category: 'home-row-basics',
        keys: ['s', 'l'],
        targetWpm: 25,
        targetAccuracy: 93,
        exercises: [
            { id: 'h10-1', text: 'sl sl sl sl sl sl sl sl', difficulty: 'beginner' },
            { id: 'h10-2', text: 'ls ls ls ls ls ls ls ls', difficulty: 'beginner' },
            { id: 'h10-3', text: 'slsl slsl slsl slsl slsl', difficulty: 'beginner' },
            { id: 'h10-4', text: 'lsls lsls lsls lsls lsls', difficulty: 'beginner' },
            { id: 'h10-5', text: 'sss lll sss lll sss lll', difficulty: 'intermediate' },
            { id: 'h10-6', text: 'slslsl slslsl slslsl slslsl', difficulty: 'intermediate' },
            { id: 'h10-7', text: 'lslsls lslsls lslsls lslsls', difficulty: 'intermediate' },
            { id: 'h10-8', text: 'ss ll ss ll ss ll ss ll', difficulty: 'intermediate' },
            { id: 'h10-9', text: 'sss lll sss lll sss lll sss lll sss lll', difficulty: 'advanced' },
            { id: 'h10-10', text: 'slslslslsl slslslslsl slslslslsl', difficulty: 'advanced' },
        ],
    },
];

export { homeRowLessons };
