import { Lesson } from '@/types';

// Home Row Intermediate & Advanced Lessons (11-20)
const homeRowAdvancedLessons: Lesson[] = [
    // Lesson 11: A Key Mastery
    {
        id: 'home-11-a',
        title: 'Master the A Key',
        description: 'Learn the A key with left pinky finger',
        category: 'home-row-intermediate',
        keys: ['a'],
        targetWpm: 20,
        targetAccuracy: 93,
        exercises: [
            { id: 'h11-1', text: 'aaa aaa aaa aaa aaa aaa aaa aaa', difficulty: 'beginner' },
            { id: 'h11-2', text: 'a a a a a a a a a a a a a a a a', difficulty: 'beginner' },
            { id: 'h11-3', text: 'aa aa aa aa aa aa aa aa aa aa', difficulty: 'beginner' },
            { id: 'h11-4', text: 'aaa a aaa a aaa a aaa a aaa a', difficulty: 'beginner' },
            { id: 'h11-5', text: 'aaaaa aaaaa aaaaa aaaaa aaaaa', difficulty: 'intermediate' },
            { id: 'h11-6', text: 'a aa aaa aaaa aaaaa a aa aaa', difficulty: 'intermediate' },
            { id: 'h11-7', text: 'aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa', difficulty: 'intermediate' },
            { id: 'h11-8', text: 'aaaaaaaaaa aaaaaaaaaa aaaaaaaaaa', difficulty: 'intermediate' },
            { id: 'h11-9', text: 'aa aa aa aa aa aa aa aa aa aa aa aa', difficulty: 'advanced' },
            { id: 'h11-10', text: 'aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa', difficulty: 'advanced' },
        ],
    },
    // Lesson 12: Semicolon Key Mastery
    {
        id: 'home-12-semi',
        title: 'Master the ; Key',
        description: 'Learn the semicolon key with right pinky finger',
        category: 'home-row-intermediate',
        keys: [';'],
        targetWpm: 18,
        targetAccuracy: 93,
        exercises: [
            { id: 'h12-1', text: ';;; ;;; ;;; ;;; ;;; ;;; ;;; ;;;', difficulty: 'beginner' },
            { id: 'h12-2', text: '; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;', difficulty: 'beginner' },
            { id: 'h12-3', text: ';; ;; ;; ;; ;; ;; ;; ;; ;; ;;', difficulty: 'beginner' },
            { id: 'h12-4', text: ';;; ; ;;; ; ;;; ; ;;; ; ;;; ;', difficulty: 'beginner' },
            { id: 'h12-5', text: ';;;;; ;;;;; ;;;;; ;;;;; ;;;;;', difficulty: 'intermediate' },
            { id: 'h12-6', text: '; ;; ;;; ;;;; ;;;;; ; ;; ;;;', difficulty: 'intermediate' },
            { id: 'h12-7', text: ';;; ;;; ;;; ;;; ;;; ;;; ;;; ;;; ;;; ;;;', difficulty: 'intermediate' },
            { id: 'h12-8', text: ';;;;;;;;;; ;;;;;;;;;; ;;;;;;;;;;', difficulty: 'intermediate' },
            { id: 'h12-9', text: ';; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;;', difficulty: 'advanced' },
            { id: 'h12-10', text: ';;; ;;; ;;; ;;; ;;; ;;; ;;; ;;; ;;; ;;;', difficulty: 'advanced' },
        ],
    },
    // Lesson 13: A and ; Combination
    {
        id: 'home-13-asemi',
        title: 'A and ; Together',
        description: 'Alternate between A and semicolon keys',
        category: 'home-row-intermediate',
        keys: ['a', ';'],
        targetWpm: 22,
        targetAccuracy: 92,
        exercises: [
            { id: 'h13-1', text: 'a; a; a; a; a; a; a; a;', difficulty: 'beginner' },
            { id: 'h13-2', text: ';a ;a ;a ;a ;a ;a ;a ;a', difficulty: 'beginner' },
            { id: 'h13-3', text: 'a;a; a;a; a;a; a;a; a;a;', difficulty: 'beginner' },
            { id: 'h13-4', text: ';a;a ;a;a ;a;a ;a;a ;a;a', difficulty: 'beginner' },
            { id: 'h13-5', text: 'aaa ;;; aaa ;;; aaa ;;;', difficulty: 'intermediate' },
            { id: 'h13-6', text: 'a;a;a; a;a;a; a;a;a; a;a;a;', difficulty: 'intermediate' },
            { id: 'h13-7', text: ';a;a;a ;a;a;a ;a;a;a ;a;a;a', difficulty: 'intermediate' },
            { id: 'h13-8', text: 'aa ;; aa ;; aa ;; aa ;;', difficulty: 'intermediate' },
            { id: 'h13-9', text: 'aaa ;;; aaa ;;; aaa ;;; aaa ;;; aaa ;;;', difficulty: 'advanced' },
            { id: 'h13-10', text: 'a;a;a;a;a; a;a;a;a;a; a;a;a;a;a;', difficulty: 'advanced' },
        ],
    },
    // Lesson 14: Left Hand Review (F, D, S, A)
    {
        id: 'home-14-left',
        title: 'Left Hand Review',
        description: 'Practice all left hand home row keys',
        category: 'home-row-intermediate',
        keys: ['f', 'd', 's', 'a'],
        targetWpm: 28,
        targetAccuracy: 91,
        exercises: [
            { id: 'h14-1', text: 'asdf asdf asdf asdf asdf asdf', difficulty: 'beginner' },
            { id: 'h14-2', text: 'fdsa fdsa fdsa fdsa fdsa fdsa', difficulty: 'beginner' },
            { id: 'h14-3', text: 'af ds af ds af ds af ds af ds', difficulty: 'beginner' },
            { id: 'h14-4', text: 'sa fd sa fd sa fd sa fd sa fd', difficulty: 'beginner' },
            { id: 'h14-5', text: 'asd fds asd fds asd fds asd fds', difficulty: 'intermediate' },
            { id: 'h14-6', text: 'asdfasdf asdfasdf asdfasdf', difficulty: 'intermediate' },
            { id: 'h14-7', text: 'fdsafdsa fdsafdsa fdsafdsa', difficulty: 'intermediate' },
            { id: 'h14-8', text: 'add dad sad fad add dad sad fad', difficulty: 'advanced' },
            { id: 'h14-9', text: 'a sad dad; add a sad fad', difficulty: 'advanced' },
            { id: 'h14-10', text: 'dad adds a sad fad; sad dad adds', difficulty: 'advanced' },
        ],
    },
    // Lesson 15: Right Hand Review (J, K, L, ;)
    {
        id: 'home-15-right',
        title: 'Right Hand Review',
        description: 'Practice all right hand home row keys',
        category: 'home-row-intermediate',
        keys: ['j', 'k', 'l', ';'],
        targetWpm: 28,
        targetAccuracy: 91,
        exercises: [
            { id: 'h15-1', text: 'jkl; jkl; jkl; jkl; jkl; jkl;', difficulty: 'beginner' },
            { id: 'h15-2', text: ';lkj ;lkj ;lkj ;lkj ;lkj ;lkj', difficulty: 'beginner' },
            { id: 'h15-3', text: 'j; kl j; kl j; kl j; kl j; kl', difficulty: 'beginner' },
            { id: 'h15-4', text: 'lk j; lk j; lk j; lk j; lk j;', difficulty: 'beginner' },
            { id: 'h15-5', text: 'jkl ;lk jkl ;lk jkl ;lk jkl ;lk', difficulty: 'intermediate' },
            { id: 'h15-6', text: 'jkl;jkl; jkl;jkl; jkl;jkl;', difficulty: 'intermediate' },
            { id: 'h15-7', text: ';lkj;lkj ;lkj;lkj ;lkj;lkj', difficulty: 'intermediate' },
            { id: 'h15-8', text: 'jj kk ll ;; jj kk ll ;; jj kk ll ;;', difficulty: 'advanced' },
            { id: 'h15-9', text: 'jkljkl; ;lkj;lkj jkljkl; ;lkj;lkj', difficulty: 'advanced' },
            { id: 'h15-10', text: 'jkl; ;lkj jkl; ;lkj jkl; ;lkj jkl;', difficulty: 'advanced' },
        ],
    },
    // Lesson 16: Full Home Row Drill
    {
        id: 'home-16-full',
        title: 'Complete Home Row',
        description: 'All home row keys together',
        category: 'home-row-advanced',
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        targetWpm: 35,
        targetAccuracy: 90,
        exercises: [
            { id: 'h16-1', text: 'asdf jkl; asdf jkl; asdf jkl;', difficulty: 'intermediate' },
            { id: 'h16-2', text: 'fdsa ;lkj fdsa ;lkj fdsa ;lkj', difficulty: 'intermediate' },
            { id: 'h16-3', text: 'aaa sss ddd fff jjj kkk lll ;;;', difficulty: 'intermediate' },
            { id: 'h16-4', text: 'asdf asdf jkl; jkl; asdf jkl;', difficulty: 'intermediate' },
            { id: 'h16-5', text: 'ffff jjjj dddd kkkk ssss llll', difficulty: 'intermediate' },
            { id: 'h16-6', text: 'asdfjkl; asdfjkl; asdfjkl;', difficulty: 'advanced' },
            { id: 'h16-7', text: 'a;sldkfj a;sldkfj a;sldkfj', difficulty: 'advanced' },
            { id: 'h16-8', text: 'asdf jkl; fdsa ;lkj asdf jkl; fdsa ;lkj', difficulty: 'advanced' },
            { id: 'h16-9', text: 'fjdk fjdk slsl slsl fjdk slsl', difficulty: 'advanced' },
            { id: 'h16-10', text: 'asdfasdf jkl;jkl; asdfasdf jkl;jkl;', difficulty: 'advanced' },
        ],
    },
    // Lesson 17: Common Home Row Words
    {
        id: 'home-17-words',
        title: 'Home Row Words',
        description: 'Type real words using home row',
        category: 'home-row-advanced',
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        targetWpm: 38,
        targetAccuracy: 92,
        exercises: [
            { id: 'h17-1', text: 'add dad sad lad fad', difficulty: 'intermediate' },
            { id: 'h17-2', text: 'all fall alls falls', difficulty: 'intermediate' },
            { id: 'h17-3', text: 'ask asks flask lass', difficulty: 'intermediate' },
            { id: 'h17-4', text: 'salad salads flask flasks', difficulty: 'intermediate' },
            { id: 'h17-5', text: 'dad asks lad for salad', difficulty: 'advanced' },
            { id: 'h17-6', text: 'a sad lad had a flask', difficulty: 'advanced' },
            { id: 'h17-7', text: 'lass falls as dad asks', difficulty: 'advanced' },
            { id: 'h17-8', text: 'all dads ask for salads', difficulty: 'advanced' },
            { id: 'h17-9', text: 'a lad falls as lass asks dad for a flask', difficulty: 'advanced' },
            { id: 'h17-10', text: 'dad had a salad and flask as lad asks lass', difficulty: 'advanced' },
        ],
    },
    // Lesson 18: Home Row Sentences
    {
        id: 'home-18-sentences',
        title: 'Home Row Sentences',
        description: 'Type complete sentences with home row',
        category: 'home-row-advanced',
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        targetWpm: 35,
        targetAccuracy: 90,
        exercises: [
            { id: 'h18-1', text: 'a dad asks; a lad falls', difficulty: 'intermediate' },
            { id: 'h18-2', text: 'sad lass asks dad; all lads fall', difficulty: 'intermediate' },
            { id: 'h18-3', text: 'flask salad; dad adds salads', difficulty: 'intermediate' },
            { id: 'h18-4', text: 'all dads; all lads; all fall', difficulty: 'intermediate' },
            { id: 'h18-5', text: 'a sad lass asks a lad; dads fall as lads ask', difficulty: 'advanced' },
            { id: 'h18-6', text: 'dad had a flask; lad asks for salad', difficulty: 'advanced' },
            { id: 'h18-7', text: 'all sad dads ask lads; lass adds flask', difficulty: 'advanced' },
            { id: 'h18-8', text: 'a flask falls as dad adds salads for all', difficulty: 'advanced' },
            { id: 'h18-9', text: 'lads fall; dads ask; lass adds a salad flask', difficulty: 'advanced' },
            { id: 'h18-10', text: 'all sad lads ask dads for salads and flasks', difficulty: 'advanced' },
        ],
    },
    // Lesson 19: Home Row Speed Drill
    {
        id: 'home-19-speed',
        title: 'Home Row Speed Drill',
        description: 'Build speed with rapid home row practice',
        category: 'home-row-advanced',
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        targetWpm: 40,
        targetAccuracy: 88,
        exercises: [
            { id: 'h19-1', text: 'asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl;', difficulty: 'intermediate' },
            { id: 'h19-2', text: 'fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj', difficulty: 'intermediate' },
            { id: 'h19-3', text: 'fj dk sl a; fj dk sl a; fj dk sl a; fj dk sl a;', difficulty: 'intermediate' },
            { id: 'h19-4', text: 'aa ss dd ff jj kk ll ;; aa ss dd ff jj kk ll ;;', difficulty: 'intermediate' },
            { id: 'h19-5', text: 'asdfjkl; asdfjkl; asdfjkl; asdfjkl; asdfjkl;', difficulty: 'advanced' },
            { id: 'h19-6', text: ';lkjfdsa ;lkjfdsa ;lkjfdsa ;lkjfdsa ;lkjfdsa', difficulty: 'advanced' },
            { id: 'h19-7', text: 'asdf fdsa jkl; ;lkj asdf fdsa jkl; ;lkj asdf', difficulty: 'advanced' },
            { id: 'h19-8', text: 'ff jj dd kk ss ll aa ;; ff jj dd kk ss ll aa ;;', difficulty: 'advanced' },
            { id: 'h19-9', text: 'fjdk slsl a;a; fjdk slsl a;a; fjdk slsl a;a;', difficulty: 'advanced' },
            { id: 'h19-10', text: 'dad ask lad; lass add flask; all fall; sad salad', difficulty: 'advanced' },
        ],
    },
    // Lesson 20: Home Row Master Challenge
    {
        id: 'home-20-master',
        title: 'Home Row Master',
        description: 'Ultimate home row mastery challenge',
        category: 'home-row-advanced',
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        targetWpm: 45,
        targetAccuracy: 92,
        exercises: [
            { id: 'h20-1', text: 'asdf jkl; fdsa ;lkj asdf jkl; fdsa ;lkj', difficulty: 'advanced' },
            { id: 'h20-2', text: 'all sad dads ask lads; lass adds flask salad', difficulty: 'advanced' },
            { id: 'h20-3', text: 'a lad falls; dad asks lass; all add salads', difficulty: 'advanced' },
            { id: 'h20-4', text: 'sad lass asks all dads; lads fall as flasks add', difficulty: 'advanced' },
            { id: 'h20-5', text: 'dad had a flask; lad asks for a salad; all fall', difficulty: 'advanced' },
            { id: 'h20-6', text: 'fjdk slsl a;a; fjdk slsl a;a; fjdk slsl a;a; fjdk', difficulty: 'advanced' },
            { id: 'h20-7', text: 'asdfjkl; ;lkjfdsa asdfjkl; ;lkjfdsa asdfjkl;', difficulty: 'advanced' },
            { id: 'h20-8', text: 'a sad lad had salad as dad asks lass for flask', difficulty: 'advanced' },
            { id: 'h20-9', text: 'all lads fall; all dads ask; all add salads and flasks', difficulty: 'advanced' },
            { id: 'h20-10', text: 'dad asks sad lad; lass falls; all add flasks and salads', difficulty: 'advanced' },
        ],
    },
];

export { homeRowAdvancedLessons };
