import { Lesson } from '@/types';

// Symbols Module - 8 Lessons
const symbolsLessons: Lesson[] = [
    // Lesson 56: Shift Key (Capital Letters)
    {
        id: 'sym-56-shift',
        title: 'Master the Shift Key',
        description: 'Learn to type capital letters',
        category: 'symbols',
        keys: ['shift'],
        targetWpm: 30,
        targetAccuracy: 90,
        exercises: [
            { id: 's56-1', text: 'Aaa Sss Ddd Fff Jjj Kkk Lll', difficulty: 'beginner' },
            { id: 's56-2', text: 'AAA SSS DDD FFF JJJ KKK LLL', difficulty: 'beginner' },
            { id: 's56-3', text: 'The The The The The The The', difficulty: 'intermediate' },
            { id: 's56-4', text: 'Hello Hello Hello Hello Hello', difficulty: 'intermediate' },
            { id: 's56-5', text: 'World World World World World', difficulty: 'intermediate' },
            { id: 's56-6', text: 'Hello World Hello World Hello', difficulty: 'intermediate' },
            { id: 's56-7', text: 'A Quick Brown Fox Jumps Over', difficulty: 'advanced' },
            { id: 's56-8', text: 'The Lazy Dog Sleeps All Day', difficulty: 'advanced' },
            { id: 's56-9', text: 'Type Fast And Accurately Always', difficulty: 'advanced' },
            { id: 's56-10', text: 'Practice Makes Perfect Every Day', difficulty: 'advanced' },
        ],
    },
    // Lesson 57: Common Punctuation
    {
        id: 'sym-57-punct',
        title: 'Common Punctuation',
        description: 'Learn period, comma, exclamation, question mark',
        category: 'symbols',
        keys: ['.', ',', '!', '?'],
        targetWpm: 25,
        targetAccuracy: 88,
        exercises: [
            { id: 's57-1', text: '. . . , , , ! ! ! ? ? ?', difficulty: 'beginner' },
            { id: 's57-2', text: 'Hello. Hi! How? Good, thanks.', difficulty: 'beginner' },
            { id: 's57-3', text: 'Stop! Wait? Go, now. Run!', difficulty: 'beginner' },
            { id: 's57-4', text: 'Is it done? Yes, it is done!', difficulty: 'intermediate' },
            { id: 's57-5', text: 'Wait, what? Really! Yes, really.', difficulty: 'intermediate' },
            { id: 's57-6', text: 'One, two, three. Ready? Go!', difficulty: 'intermediate' },
            { id: 's57-7', text: 'Hello! How are you? I am fine, thanks.', difficulty: 'advanced' },
            { id: 's57-8', text: 'Wow! That is amazing, right? Yes!', difficulty: 'advanced' },
            { id: 's57-9', text: 'Stop, look, and listen! Ready? Yes!', difficulty: 'advanced' },
            { id: 's57-10', text: 'Wait! What happened? Nothing, just testing.', difficulty: 'advanced' },
        ],
    },
    // Lesson 58: Brackets and Parentheses
    {
        id: 'sym-58-brackets',
        title: 'Brackets and Parentheses',
        description: 'Learn ( ) [ ] { }',
        category: 'symbols',
        keys: ['(', ')', '[', ']', '{', '}'],
        targetWpm: 20,
        targetAccuracy: 85,
        exercises: [
            { id: 's58-1', text: '( ) ( ) ( ) ( ) ( ) ( )', difficulty: 'beginner' },
            { id: 's58-2', text: '[ ] [ ] [ ] [ ] [ ] [ ]', difficulty: 'beginner' },
            { id: 's58-3', text: '{ } { } { } { } { } { }', difficulty: 'beginner' },
            { id: 's58-4', text: '() () () [] [] [] {} {} {}', difficulty: 'beginner' },
            { id: 's58-5', text: '(a) [b] {c} (d) [e] {f}', difficulty: 'intermediate' },
            { id: 's58-6', text: '(one) [two] {three} (four)', difficulty: 'intermediate' },
            { id: 's58-7', text: 'function() { return [1]; }', difficulty: 'advanced' },
            { id: 's58-8', text: 'if (x) { y = [1, 2, 3]; }', difficulty: 'advanced' },
            { id: 's58-9', text: 'array[0] = (a + b) * {c};', difficulty: 'advanced' },
            { id: 's58-10', text: 'obj = { key: (val), arr: [1] };', difficulty: 'advanced' },
        ],
    },
    // Lesson 59: Quotes and Apostrophes
    {
        id: 'sym-59-quotes',
        title: 'Quotes and Apostrophes',
        description: 'Learn single and double quotes',
        category: 'symbols',
        keys: ["'", '"'],
        targetWpm: 22,
        targetAccuracy: 88,
        exercises: [
            { id: 's59-1', text: "' ' ' ' ' ' ' ' ' ' ' '", difficulty: 'beginner' },
            { id: 's59-2', text: '" " " " " " " " " " " "', difficulty: 'beginner' },
            { id: 's59-3', text: "'a' 'b' 'c' 'd' 'e' 'f'", difficulty: 'beginner' },
            { id: 's59-4', text: '"hello" "world" "test"', difficulty: 'beginner' },
            { id: 's59-5', text: "it's can't won't don't", difficulty: 'intermediate' },
            { id: 's59-6', text: '"Hello," she said. "Hi!"', difficulty: 'intermediate' },
            { id: 's59-7', text: "He said, 'It's fine.'", difficulty: 'advanced' },
            { id: 's59-8', text: '"What\'s this?" asked Tom.', difficulty: 'advanced' },
            { id: 's59-9', text: "const x = 'hello'; let y = \"world\";", difficulty: 'advanced' },
            { id: 's59-10', text: '"I\'m ready," she said. \'Let\'s go!\'', difficulty: 'advanced' },
        ],
    },
    // Lesson 60: Math Symbols
    {
        id: 'sym-60-math',
        title: 'Math Symbols',
        description: 'Learn + - * / = symbols',
        category: 'symbols',
        keys: ['+', '-', '*', '/', '='],
        targetWpm: 22,
        targetAccuracy: 88,
        exercises: [
            { id: 's60-1', text: '+ + + - - - * * * / / / = = =', difficulty: 'beginner' },
            { id: 's60-2', text: '1 + 1 = 2; 2 - 1 = 1', difficulty: 'beginner' },
            { id: 's60-3', text: '2 * 3 = 6; 6 / 2 = 3', difficulty: 'beginner' },
            { id: 's60-4', text: '+ - * / = + - * / =', difficulty: 'beginner' },
            { id: 's60-5', text: '10 + 20 = 30; 50 - 20 = 30', difficulty: 'intermediate' },
            { id: 's60-6', text: '5 * 5 = 25; 100 / 4 = 25', difficulty: 'intermediate' },
            { id: 's60-7', text: 'x = 10 + 5 - 3 * 2 / 1', difficulty: 'advanced' },
            { id: 's60-8', text: 'total = price * qty - discount', difficulty: 'advanced' },
            { id: 's60-9', text: 'a + b = c; c - a = b; b * 2 = d', difficulty: 'advanced' },
            { id: 's60-10', text: 'result = (a + b) * c / d - e', difficulty: 'advanced' },
        ],
    },
    // Lesson 61: Special Characters
    {
        id: 'sym-61-special',
        title: 'Special Characters',
        description: 'Learn @ # $ % symbols',
        category: 'symbols',
        keys: ['@', '#', '$', '%'],
        targetWpm: 20,
        targetAccuracy: 85,
        exercises: [
            { id: 's61-1', text: '@ @ @ # # # $ $ $ % % %', difficulty: 'beginner' },
            { id: 's61-2', text: '@@ ## $$ %% @@ ## $$ %%', difficulty: 'beginner' },
            { id: 's61-3', text: '@# $% @# $% @# $% @# $%', difficulty: 'beginner' },
            { id: 's61-4', text: 'user@email.com user@test.com', difficulty: 'intermediate' },
            { id: 's61-5', text: '#tag #code #type #fast', difficulty: 'intermediate' },
            { id: 's61-6', text: '$100 $200 $500 $1000', difficulty: 'intermediate' },
            { id: 's61-7', text: '50% off! 25% discount! 10% tax', difficulty: 'advanced' },
            { id: 's61-8', text: 'email@domain.com #hashtag $price', difficulty: 'advanced' },
            { id: 's61-9', text: '@user sent $50 with 10% fee #payment', difficulty: 'advanced' },
            { id: 's61-10', text: 'Price: $99.99 (20% off!) @store #sale', difficulty: 'advanced' },
        ],
    },
    // Lesson 62: Advanced Symbols
    {
        id: 'sym-62-advanced',
        title: 'Advanced Symbols',
        description: 'Learn & ^ ~ ` symbols',
        category: 'symbols',
        keys: ['&', '^', '~', '`'],
        targetWpm: 18,
        targetAccuracy: 85,
        exercises: [
            { id: 's62-1', text: '& & & ^ ^ ^ ~ ~ ~ ` ` `', difficulty: 'beginner' },
            { id: 's62-2', text: '&& ^^ ~~ `` && ^^ ~~ ``', difficulty: 'beginner' },
            { id: 's62-3', text: '&^ ~` &^ ~` &^ ~` &^ ~`', difficulty: 'beginner' },
            { id: 's62-4', text: 'fish & chips; salt & pepper', difficulty: 'intermediate' },
            { id: 's62-5', text: '2^8 = 256; 10^2 = 100', difficulty: 'intermediate' },
            { id: 's62-6', text: '~home ~user ~documents', difficulty: 'intermediate' },
            { id: 's62-7', text: '`code` `text` `value`', difficulty: 'advanced' },
            { id: 's62-8', text: 'if (a && b) { c = a ^ b; }', difficulty: 'advanced' },
            { id: 's62-9', text: 'const x = `hello ${name}`;', difficulty: 'advanced' },
            { id: 's62-10', text: 'path = ~/docs && file^2 = `result`', difficulty: 'advanced' },
        ],
    },
    // Lesson 63: All Symbols Master
    {
        id: 'sym-63-master',
        title: 'All Symbols Master',
        description: 'Master all symbol keys',
        category: 'symbols',
        keys: ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '=', '+'],
        targetWpm: 25,
        targetAccuracy: 85,
        exercises: [
            { id: 's63-1', text: '!@#$%^&*() !@#$%^&*()', difficulty: 'intermediate' },
            { id: 's63-2', text: '-_=+ -_=+ -_=+ -_=+ -_=+', difficulty: 'intermediate' },
            { id: 's63-3', text: '!@#$ %^&* ()_+ !@#$ %^&*', difficulty: 'intermediate' },
            { id: 's63-4', text: 'email@test.com #tag $100 50%', difficulty: 'intermediate' },
            { id: 's63-5', text: 'Hello! How are you? I\'m fine.', difficulty: 'advanced' },
            { id: 's63-6', text: 'Price: $99.99 (20% off!) @store', difficulty: 'advanced' },
            { id: 's63-7', text: 'if (x && y) { z = a ^ b; }', difficulty: 'advanced' },
            { id: 's63-8', text: 'const str = `${a} + ${b} = ${c}`;', difficulty: 'advanced' },
            { id: 's63-9', text: '!@#$%^&*()-_=+[]{}|;:\'",.<>/?', difficulty: 'advanced' },
            { id: 's63-10', text: 'user@email.com said: "It\'s $50 (25% off)!"', difficulty: 'advanced' },
        ],
    },
];

export { symbolsLessons };
