import { Lesson } from '@/types';

// Top Row Module - 15 Lessons
const topRowLessons: Lesson[] = [
    // Lesson 21: G Key (extends from F)
    {
        id: 'top-21-g',
        title: 'Master the G Key',
        description: 'Learn G key extending from F with left index',
        category: 'top-row-basics',
        keys: ['g', 'f'],
        targetWpm: 25,
        targetAccuracy: 93,
        exercises: [
            { id: 't21-1', text: 'ggg ggg ggg ggg ggg ggg', difficulty: 'beginner' },
            { id: 't21-2', text: 'fgf fgf fgf fgf fgf fgf', difficulty: 'beginner' },
            { id: 't21-3', text: 'gfg gfg gfg gfg gfg gfg', difficulty: 'beginner' },
            { id: 't21-4', text: 'fg fg fg fg fg fg fg fg', difficulty: 'beginner' },
            { id: 't21-5', text: 'gf gf gf gf gf gf gf gf', difficulty: 'intermediate' },
            { id: 't21-6', text: 'gggg ffff gggg ffff gggg', difficulty: 'intermediate' },
            { id: 't21-7', text: 'fgfg fgfg fgfg fgfg fgfg', difficulty: 'intermediate' },
            { id: 't21-8', text: 'gfgf gfgf gfgf gfgf gfgf', difficulty: 'intermediate' },
            { id: 't21-9', text: 'flag flags gag gags sag', difficulty: 'advanced' },
            { id: 't21-10', text: 'glad gag slag lags glass', difficulty: 'advanced' },
        ],
    },
    // Lesson 22: H Key (extends from J)
    {
        id: 'top-22-h',
        title: 'Master the H Key',
        description: 'Learn H key extending from J with right index',
        category: 'top-row-basics',
        keys: ['h', 'j'],
        targetWpm: 25,
        targetAccuracy: 93,
        exercises: [
            { id: 't22-1', text: 'hhh hhh hhh hhh hhh hhh', difficulty: 'beginner' },
            { id: 't22-2', text: 'jhj jhj jhj jhj jhj jhj', difficulty: 'beginner' },
            { id: 't22-3', text: 'hjh hjh hjh hjh hjh hjh', difficulty: 'beginner' },
            { id: 't22-4', text: 'hj hj hj hj hj hj hj hj', difficulty: 'beginner' },
            { id: 't22-5', text: 'jh jh jh jh jh jh jh jh', difficulty: 'intermediate' },
            { id: 't22-6', text: 'hhhh jjjj hhhh jjjj hhhh', difficulty: 'intermediate' },
            { id: 't22-7', text: 'hjhj hjhj hjhj hjhj hjhj', difficulty: 'intermediate' },
            { id: 't22-8', text: 'jhjh jhjh jhjh jhjh jhjh', difficulty: 'intermediate' },
            { id: 't22-9', text: 'half hash dash shall', difficulty: 'advanced' },
            { id: 't22-10', text: 'had hall halls flash hash', difficulty: 'advanced' },
        ],
    },
    // Lesson 23: G and H Combination
    {
        id: 'top-23-gh',
        title: 'G and H Together',
        description: 'Practice G and H keys together',
        category: 'top-row-basics',
        keys: ['g', 'h', 'f', 'j'],
        targetWpm: 28,
        targetAccuracy: 92,
        exercises: [
            { id: 't23-1', text: 'gh gh gh gh gh gh gh gh', difficulty: 'beginner' },
            { id: 't23-2', text: 'hg hg hg hg hg hg hg hg', difficulty: 'beginner' },
            { id: 't23-3', text: 'fghj fghj fghj fghj fghj', difficulty: 'beginner' },
            { id: 't23-4', text: 'jhgf jhgf jhgf jhgf jhgf', difficulty: 'beginner' },
            { id: 't23-5', text: 'ghgh ghgh ghgh ghgh ghgh', difficulty: 'intermediate' },
            { id: 't23-6', text: 'hghg hghg hghg hghg hghg', difficulty: 'intermediate' },
            { id: 't23-7', text: 'fgfg hjhj fgfg hjhj fgfg', difficulty: 'intermediate' },
            { id: 't23-8', text: 'high sigh flash glass', difficulty: 'advanced' },
            { id: 't23-9', text: 'half a glass; high flags', difficulty: 'advanced' },
            { id: 't23-10', text: 'flash light; high hall glass', difficulty: 'advanced' },
        ],
    },
    // Lesson 24: R Key
    {
        id: 'top-24-r',
        title: 'Master the R Key',
        description: 'Learn R key extending from F',
        category: 'top-row-basics',
        keys: ['r', 'f'],
        targetWpm: 25,
        targetAccuracy: 93,
        exercises: [
            { id: 't24-1', text: 'rrr rrr rrr rrr rrr rrr', difficulty: 'beginner' },
            { id: 't24-2', text: 'frf frf frf frf frf frf', difficulty: 'beginner' },
            { id: 't24-3', text: 'rfr rfr rfr rfr rfr rfr', difficulty: 'beginner' },
            { id: 't24-4', text: 'rf rf rf rf rf rf rf rf', difficulty: 'beginner' },
            { id: 't24-5', text: 'fr fr fr fr fr fr fr fr', difficulty: 'intermediate' },
            { id: 't24-6', text: 'rrrr ffff rrrr ffff rrrr', difficulty: 'intermediate' },
            { id: 't24-7', text: 'rfrf rfrf rfrf rfrf rfrf', difficulty: 'intermediate' },
            { id: 't24-8', text: 'raft draft rash rush red', difficulty: 'advanced' },
            { id: 't24-9', text: 'grade grass grace glass', difficulty: 'advanced' },
            { id: 't24-10', text: 'rare dark ark far radar', difficulty: 'advanced' },
        ],
    },
    // Lesson 25: U Key
    {
        id: 'top-25-u',
        title: 'Master the U Key',
        description: 'Learn U key extending from J',
        category: 'top-row-basics',
        keys: ['u', 'j'],
        targetWpm: 25,
        targetAccuracy: 93,
        exercises: [
            { id: 't25-1', text: 'uuu uuu uuu uuu uuu uuu', difficulty: 'beginner' },
            { id: 't25-2', text: 'juj juj juj juj juj juj', difficulty: 'beginner' },
            { id: 't25-3', text: 'uju uju uju uju uju uju', difficulty: 'beginner' },
            { id: 't25-4', text: 'uj uj uj uj uj uj uj uj', difficulty: 'beginner' },
            { id: 't25-5', text: 'ju ju ju ju ju ju ju ju', difficulty: 'intermediate' },
            { id: 't25-6', text: 'uuuu jjjj uuuu jjjj uuuu', difficulty: 'intermediate' },
            { id: 't25-7', text: 'ujuj ujuj ujuj ujuj ujuj', difficulty: 'intermediate' },
            { id: 't25-8', text: 'juju juju juju juju juju', difficulty: 'intermediate' },
            { id: 't25-9', text: 'just jug jump hug hurl', difficulty: 'advanced' },
            { id: 't25-10', text: 'full dull hull lull skull', difficulty: 'advanced' },
        ],
    },
    // Lesson 26: R and U Combination
    {
        id: 'top-26-ru',
        title: 'R and U Together',
        description: 'Practice R and U keys together',
        category: 'top-row-intermediate',
        keys: ['r', 'u', 'f', 'j'],
        targetWpm: 28,
        targetAccuracy: 92,
        exercises: [
            { id: 't26-1', text: 'ru ru ru ru ru ru ru ru', difficulty: 'beginner' },
            { id: 't26-2', text: 'ur ur ur ur ur ur ur ur', difficulty: 'beginner' },
            { id: 't26-3', text: 'ruru ruru ruru ruru ruru', difficulty: 'beginner' },
            { id: 't26-4', text: 'urur urur urur urur urur', difficulty: 'beginner' },
            { id: 't26-5', text: 'rush hurl rural hurra', difficulty: 'intermediate' },
            { id: 't26-6', text: 'fur fur fur fur fur fur', difficulty: 'intermediate' },
            { id: 't26-7', text: 'ruff ruff gruff stuff', difficulty: 'intermediate' },
            { id: 't26-8', text: 'sure sure sure sure sure', difficulty: 'advanced' },
            { id: 't26-9', text: 'rural rural rural rural', difficulty: 'advanced' },
            { id: 't26-10', text: 'hurrah hurrah rush fur gruff', difficulty: 'advanced' },
        ],
    },
    // Lesson 27: E Key
    {
        id: 'top-27-e',
        title: 'Master the E Key',
        description: 'Learn E key extending from D',
        category: 'top-row-intermediate',
        keys: ['e', 'd'],
        targetWpm: 28,
        targetAccuracy: 93,
        exercises: [
            { id: 't27-1', text: 'eee eee eee eee eee eee', difficulty: 'beginner' },
            { id: 't27-2', text: 'ded ded ded ded ded ded', difficulty: 'beginner' },
            { id: 't27-3', text: 'ede ede ede ede ede ede', difficulty: 'beginner' },
            { id: 't27-4', text: 'ed ed ed ed ed ed ed ed', difficulty: 'beginner' },
            { id: 't27-5', text: 'de de de de de de de de', difficulty: 'intermediate' },
            { id: 't27-6', text: 'eeee dddd eeee dddd eeee', difficulty: 'intermediate' },
            { id: 't27-7', text: 'edde edde edde edde edde', difficulty: 'intermediate' },
            { id: 't27-8', text: 'feed seed deed need lead', difficulty: 'advanced' },
            { id: 't27-9', text: 'free feel flee seed read', difficulty: 'advanced' },
            { id: 't27-10', text: 'free the deer; feed the seeds', difficulty: 'advanced' },
        ],
    },
    // Lesson 28: I Key
    {
        id: 'top-28-i',
        title: 'Master the I Key',
        description: 'Learn I key extending from K',
        category: 'top-row-intermediate',
        keys: ['i', 'k'],
        targetWpm: 28,
        targetAccuracy: 93,
        exercises: [
            { id: 't28-1', text: 'iii iii iii iii iii iii', difficulty: 'beginner' },
            { id: 't28-2', text: 'kik kik kik kik kik kik', difficulty: 'beginner' },
            { id: 't28-3', text: 'iki iki iki iki iki iki', difficulty: 'beginner' },
            { id: 't28-4', text: 'ik ik ik ik ik ik ik ik', difficulty: 'beginner' },
            { id: 't28-5', text: 'ki ki ki ki ki ki ki ki', difficulty: 'intermediate' },
            { id: 't28-6', text: 'iiii kkkk iiii kkkk iiii', difficulty: 'intermediate' },
            { id: 't28-7', text: 'ikki ikki ikki ikki ikki', difficulty: 'intermediate' },
            { id: 't28-8', text: 'like silk hike like kite', difficulty: 'advanced' },
            { id: 't28-9', text: 'guide slide glide side hide', difficulty: 'advanced' },
            { id: 't28-10', text: 'rigid kid lid did hill skill', difficulty: 'advanced' },
        ],
    },
    // Lesson 29: E and I Combination
    {
        id: 'top-29-ei',
        title: 'E and I Together',
        description: 'Practice E and I keys together',
        category: 'top-row-intermediate',
        keys: ['e', 'i', 'd', 'k'],
        targetWpm: 30,
        targetAccuracy: 91,
        exercises: [
            { id: 't29-1', text: 'ei ei ei ei ei ei ei ei', difficulty: 'beginner' },
            { id: 't29-2', text: 'ie ie ie ie ie ie ie ie', difficulty: 'beginner' },
            { id: 't29-3', text: 'eiei eiei eiei eiei eiei', difficulty: 'beginner' },
            { id: 't29-4', text: 'ieie ieie ieie ieie ieie', difficulty: 'beginner' },
            { id: 't29-5', text: 'die die lie lie tie tie', difficulty: 'intermediate' },
            { id: 't29-6', text: 'idle idle rifle rifle', difficulty: 'intermediate' },
            { id: 't29-7', text: 'field field shield shield', difficulty: 'intermediate' },
            { id: 't29-8', text: 'either either neither either', difficulty: 'advanced' },
            { id: 't29-9', text: 'their their heirs heirs', difficulty: 'advanced' },
            { id: 't29-10', text: 'tie the field; rifle idle shield', difficulty: 'advanced' },
        ],
    },
    // Lesson 30: T Key
    {
        id: 'top-30-t',
        title: 'Master the T Key',
        description: 'Learn T key extending from F',
        category: 'top-row-intermediate',
        keys: ['t', 'f'],
        targetWpm: 28,
        targetAccuracy: 93,
        exercises: [
            { id: 't30-1', text: 'ttt ttt ttt ttt ttt ttt', difficulty: 'beginner' },
            { id: 't30-2', text: 'ftf ftf ftf ftf ftf ftf', difficulty: 'beginner' },
            { id: 't30-3', text: 'tft tft tft tft tft tft', difficulty: 'beginner' },
            { id: 't30-4', text: 'tf tf tf tf tf tf tf tf', difficulty: 'beginner' },
            { id: 't30-5', text: 'ft ft ft ft ft ft ft ft', difficulty: 'intermediate' },
            { id: 't30-6', text: 'tttt ffff tttt ffff tttt', difficulty: 'intermediate' },
            { id: 't30-7', text: 'tftf tftf tftf tftf tftf', difficulty: 'intermediate' },
            { id: 't30-8', text: 'the that this these there', difficulty: 'advanced' },
            { id: 't30-9', text: 'fast last test rest latest', difficulty: 'advanced' },
            { id: 't30-10', text: 'the test; that first taste', difficulty: 'advanced' },
        ],
    },
    // Lesson 31: Y Key
    {
        id: 'top-31-y',
        title: 'Master the Y Key',
        description: 'Learn Y key extending from J',
        category: 'top-row-advanced',
        keys: ['y', 'j'],
        targetWpm: 28,
        targetAccuracy: 92,
        exercises: [
            { id: 't31-1', text: 'yyy yyy yyy yyy yyy yyy', difficulty: 'beginner' },
            { id: 't31-2', text: 'jyj jyj jyj jyj jyj jyj', difficulty: 'beginner' },
            { id: 't31-3', text: 'yjy yjy yjy yjy yjy yjy', difficulty: 'beginner' },
            { id: 't31-4', text: 'yj yj yj yj yj yj yj yj', difficulty: 'beginner' },
            { id: 't31-5', text: 'jy jy jy jy jy jy jy jy', difficulty: 'intermediate' },
            { id: 't31-6', text: 'yyyy jjjj yyyy jjjj yyyy', difficulty: 'intermediate' },
            { id: 't31-7', text: 'yjyj yjyj yjyj yjyj yjyj', difficulty: 'intermediate' },
            { id: 't31-8', text: 'yet yes yell year yeast', difficulty: 'advanced' },
            { id: 't31-9', text: 'they grey tray day stay', difficulty: 'advanced' },
            { id: 't31-10', text: 'stay yet; they say yes', difficulty: 'advanced' },
        ],
    },
    // Lesson 32: W Key
    {
        id: 'top-32-w',
        title: 'Master the W Key',
        description: 'Learn W key extending from S',
        category: 'top-row-advanced',
        keys: ['w', 's'],
        targetWpm: 28,
        targetAccuracy: 92,
        exercises: [
            { id: 't32-1', text: 'www www www www www www', difficulty: 'beginner' },
            { id: 't32-2', text: 'sws sws sws sws sws sws', difficulty: 'beginner' },
            { id: 't32-3', text: 'wsw wsw wsw wsw wsw wsw', difficulty: 'beginner' },
            { id: 't32-4', text: 'ws ws ws ws ws ws ws ws', difficulty: 'beginner' },
            { id: 't32-5', text: 'sw sw sw sw sw sw sw sw', difficulty: 'intermediate' },
            { id: 't32-6', text: 'wwww ssss wwww ssss wwww', difficulty: 'intermediate' },
            { id: 't32-7', text: 'swsw swsw swsw swsw swsw', difficulty: 'intermediate' },
            { id: 't32-8', text: 'was were with wide swift', difficulty: 'advanced' },
            { id: 't32-9', text: 'sweet swirl swell sweet', difficulty: 'advanced' },
            { id: 't32-10', text: 'sweet water was swift', difficulty: 'advanced' },
        ],
    },
    // Lesson 33: O Key
    {
        id: 'top-33-o',
        title: 'Master the O Key',
        description: 'Learn O key extending from L',
        category: 'top-row-advanced',
        keys: ['o', 'l'],
        targetWpm: 28,
        targetAccuracy: 92,
        exercises: [
            { id: 't33-1', text: 'ooo ooo ooo ooo ooo ooo', difficulty: 'beginner' },
            { id: 't33-2', text: 'lol lol lol lol lol lol', difficulty: 'beginner' },
            { id: 't33-3', text: 'olo olo olo olo olo olo', difficulty: 'beginner' },
            { id: 't33-4', text: 'lo lo lo lo lo lo lo lo', difficulty: 'beginner' },
            { id: 't33-5', text: 'ol ol ol ol ol ol ol ol', difficulty: 'intermediate' },
            { id: 't33-6', text: 'oooo llll oooo llll oooo', difficulty: 'intermediate' },
            { id: 't33-7', text: 'olol olol olol olol olol', difficulty: 'intermediate' },
            { id: 't33-8', text: 'old hold gold fold told', difficulty: 'advanced' },
            { id: 't33-9', text: 'tool fool cool drool stool', difficulty: 'advanced' },
            { id: 't33-10', text: 'old gold tool; hold the drool', difficulty: 'advanced' },
        ],
    },
    // Lesson 34: Q Key
    {
        id: 'top-34-q',
        title: 'Master the Q Key',
        description: 'Learn Q key extending from A',
        category: 'top-row-advanced',
        keys: ['q', 'a', 'u'],
        targetWpm: 25,
        targetAccuracy: 90,
        exercises: [
            { id: 't34-1', text: 'qqq qqq qqq qqq qqq qqq', difficulty: 'beginner' },
            { id: 't34-2', text: 'aqa aqa aqa aqa aqa aqa', difficulty: 'beginner' },
            { id: 't34-3', text: 'qaq qaq qaq qaq qaq qaq', difficulty: 'beginner' },
            { id: 't34-4', text: 'qu qu qu qu qu qu qu qu', difficulty: 'beginner' },
            { id: 't34-5', text: 'qua qua qua qua qua qua', difficulty: 'intermediate' },
            { id: 't34-6', text: 'qqqq aaaa qqqq aaaa qqqq', difficulty: 'intermediate' },
            { id: 't34-7', text: 'ququ ququ ququ ququ ququ', difficulty: 'intermediate' },
            { id: 't34-8', text: 'quite quiet quest quilt', difficulty: 'advanced' },
            { id: 't34-9', text: 'squad squid equal sequel', difficulty: 'advanced' },
            { id: 't34-10', text: 'quite a quest; the quiet squad', difficulty: 'advanced' },
        ],
    },
    // Lesson 35: P Key
    {
        id: 'top-35-p',
        title: 'Master the P Key',
        description: 'Learn P key extending from semicolon',
        category: 'top-row-advanced',
        keys: ['p', ';'],
        targetWpm: 25,
        targetAccuracy: 90,
        exercises: [
            { id: 't35-1', text: 'ppp ppp ppp ppp ppp ppp', difficulty: 'beginner' },
            { id: 't35-2', text: ';p; ;p; ;p; ;p; ;p; ;p;', difficulty: 'beginner' },
            { id: 't35-3', text: 'p;p p;p p;p p;p p;p p;p', difficulty: 'beginner' },
            { id: 't35-4', text: 'p; p; p; p; p; p; p; p;', difficulty: 'beginner' },
            { id: 't35-5', text: ';p ;p ;p ;p ;p ;p ;p ;p', difficulty: 'intermediate' },
            { id: 't35-6', text: 'pppp ;;;; pppp ;;;; pppp', difficulty: 'intermediate' },
            { id: 't35-7', text: 'p;p; p;p; p;p; p;p; p;p;', difficulty: 'intermediate' },
            { id: 't35-8', text: 'pull push put pass pay', difficulty: 'advanced' },
            { id: 't35-9', text: 'plop plop slip slap step', difficulty: 'advanced' },
            { id: 't35-10', text: 'push pull; put the play; pay up', difficulty: 'advanced' },
        ],
    },
];

export { topRowLessons };
